### ISSUE TITLE
Uberwar ignores some profiles

### ISSUE THREAD

**Issue by curtosis** [luminus-framework/lein-uberwar#1]
The extracted task appears to share the same issue as the ring task: https://github.com/weavejester/lein-ring/issues/163

**Comment by yogthos** [comment]
I won't have time to look at this in the near future, any chance you'd be interested in making a pr for a fix?

**Comment by curtosis** [comment]
I'll take a look and see if I can figure out what's going on. Not committing to anything yet, though!

**Comment by yogthos** [comment]
Sounds great :)

**Comment by hanshuebner** [comment]
https://github.com/luminus-framework/lein-uberwar/commit/34efc38401169dedd2e8e1057f41b3339406ab3d should fix this issue.

**Comment by yogthos** [comment]
:+1:
